'use client';

import { FaInfoCircle, FaExclamationTriangle, FaTimesCircle } from "react-icons/fa";

export default function Logs() {
  const logs = [
    { timestamp: '2024-06-01 12:00', level: 'INFO', message: 'Scraping started', source: 'Bot A' },
    { timestamp: '2024-06-01 12:05', level: 'WARN', message: 'Slow response from MangaDex', source: 'Bot A' },
    { timestamp: '2024-06-01 12:10', level: 'ERROR', message: 'Failed to fetch from MangaFox', source: 'Bot C' },
    { timestamp: '2024-06-01 12:15', level: 'INFO', message: 'Scraping finished', source: 'Bot A' },
    { timestamp: '2024-06-01 12:20', level: 'WARN', message: 'Proxy timeout', source: 'Bot B' },
  ];
  const infoCount = logs.filter(l => l.level === 'INFO').length;
  const warnCount = logs.filter(l => l.level === 'WARN').length;
  const errorCount = logs.filter(l => l.level === 'ERROR').length;

  function logLevelBadge(level) {
    if (level === 'INFO') return <span className="inline-flex items-center px-2 py-0.5 rounded bg-blue-100 text-blue-800 text-xs font-semibold"><FaInfoCircle className="mr-1" />Info</span>;
    if (level === 'WARN') return <span className="inline-flex items-center px-2 py-0.5 rounded bg-yellow-100 text-yellow-800 text-xs font-semibold"><FaExclamationTriangle className="mr-1" />Warn</span>;
    if (level === 'ERROR') return <span className="inline-flex items-center px-2 py-0.5 rounded bg-red-100 text-red-800 text-xs font-semibold"><FaTimesCircle className="mr-1" />Error</span>;
    return level;
  }

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">Logs</h1>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div className="flex items-center p-4 bg-white dark:bg-gray-800 rounded-lg shadow">
          <FaInfoCircle className="w-6 h-6 text-blue-500 mr-3" />
          <div>
            <div className="text-gray-500 text-sm">Info</div>
            <div className="text-xl font-bold">{infoCount}</div>
          </div>
        </div>
        <div className="flex items-center p-4 bg-white dark:bg-gray-800 rounded-lg shadow">
          <FaExclamationTriangle className="w-6 h-6 text-yellow-500 mr-3" />
          <div>
            <div className="text-gray-500 text-sm">Warnings</div>
            <div className="text-xl font-bold">{warnCount}</div>
          </div>
        </div>
        <div className="flex items-center p-4 bg-white dark:bg-gray-800 rounded-lg shadow">
          <FaTimesCircle className="w-6 h-6 text-red-500 mr-3" />
          <div>
            <div className="text-gray-500 text-sm">Errors</div>
            <div className="text-xl font-bold">{errorCount}</div>
          </div>
        </div>
      </div>
      <p className="mb-4 text-gray-600 dark:text-gray-300">View logs generated by the manga bot and its components.</p>
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
        <table className="w-full text-sm text-left">
          <thead>
            <tr className="text-gray-500 dark:text-gray-400">
              <th className="py-2">Timestamp</th>
              <th className="py-2">Level</th>
              <th className="py-2">Message</th>
              <th className="py-2">Source</th>
            </tr>
          </thead>
          <tbody>
            {logs.map((log, idx) => (
              <tr key={idx} className="border-t border-gray-200 dark:border-gray-700">
                <td className="py-2">{log.timestamp}</td>
                <td className="py-2">{logLevelBadge(log.level)}</td>
                <td className="py-2">{log.message}</td>
                <td className="py-2">{log.source}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
} 